import { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';

export type Language = 'en' | 'hi' | 'ur' | 'te' | 'kn' | 'ta' | 'ml' | 'mr' | 'gu' | 'pa' | 'bn';

interface LanguageLabels {
  [key: string]: string;
}

const en: LanguageLabels = {
  // Common
  dashboard: 'Dashboard', settings: 'Settings', logout: 'Log out', save: 'Save', cancel: 'Cancel', submit: 'Submit', loading: 'Loading...', search: 'Search', actions: 'Actions', status: 'Status', date: 'Date', name: 'Name', email: 'Email', mobile: 'Mobile', language: 'Language', edit: 'Edit', delete: 'Delete', active: 'Active', paused: 'Paused', notSet: 'Not set', verified: 'Verified',
  // Auth
  login: 'Log in', register: 'Get Started', signUp: 'Sign Up',
  // User Dashboard
  welcomeBack: 'Welcome back', medicineOverview: "Here's your medicine overview", totalMedicines: 'Total Medicines', expiringSoon: 'Expiring Soon', expired: 'Expired', lowStock: 'Low Stock', quickActions: 'Quick Actions', scanQR: 'Scan QR', manualEntry: 'Manual Entry', bookTest: 'Book Test', addMedicine: 'Add Medicine', myMedicines: 'My Medicines', myBloodTestBookings: 'My Blood Test Bookings', myRestockRequests: 'My Restock Requests', noBookingsYet: 'No blood test bookings yet.', noMedicinesYet: 'No medicines added yet. Add your first medicine to start tracking.', restockNow: 'Restock', outOfStock: 'Out of stock', confirmed: 'Confirmed',
  // Navigation sections
  medicineReminders: 'Medicine Reminders', restockRequests: 'Restock Requests', bloodTestBookings: 'Blood Test Bookings', notifications: 'Notifications', profile: 'Profile', personalInfo: 'Personal Information', profileUpdated: 'Profile Updated',
  // Reminders
  addReminder: 'Add Reminder', reminderAdded: 'Reminder Added', reminderDeleted: 'Reminder Deleted', noReminders: 'No reminders set. Add a reminder to get daily medicine notifications.', reminderTime: 'Reminder Time', reminder: 'Reminder', timeToTakeMedicine: 'Time to take your medicine',
  // Notifications
  markAllRead: 'Mark All Read', noNotifications: 'No notifications yet.',
  // Requests
  activeRequests: 'Active Requests', completedRequests: 'Completed Requests', noRestockRequests: 'No restock requests yet.', activeBookings: 'Active Bookings', completedBookings: 'Completed Bookings',
  // Booking
  bookBloodTest: 'Book Blood Test', testType: 'Test Type', selectTestType: 'Select test type', preferredDate: 'Preferred Date', preferredTime: 'Preferred Time', additionalNotes: 'Additional Notes', bookingCreated: 'Blood Test Booking Created Successfully', bookingDesc: 'Your booking request has been sent to diagnostic centres.', bookAppointment: 'Book Appointment', booking: 'Booking...',
  // Medicine
  medicineName: 'Medicine Name', batchNumber: 'Batch Number', expiryDate: 'Expiry Date', quantity: 'Quantity', dosage: 'Dosage', prescribedDoses: 'Prescribed Doses', medicineAdded: 'Medicine Added', addMedicineTitle: 'Add Medicine', qrScan: 'QR Scan', manual: 'Manual', simulateQR: 'Simulate QR Scan', qrScanned: 'QR Scanned', qrDesc: 'Medicine details populated. Review and save.', cameraNotAvailable: 'Camera not available in this environment.', clickSimulate: 'Click below to simulate a scan.',
  // Adherence
  adherence: 'Adherence', takeDose: 'Take Dose', doseTaken: 'Dose Recorded', doseDesc: 'Your adherence has been updated.', adherenceScore: 'Adherence Score',
  // Pharmacy
  pharmacyDashboard: 'Pharmacy Dashboard', manageInventory: 'Manage your inventory and sales', totalItems: 'Total Items', inventoryValue: 'Inventory Value', sellMedicine: 'Sell Medicine', addInventory: 'Add Inventory', csvUpload: 'CSV Upload', pendingRestocks: 'Pending Restock Requests', accept: 'Accept', reject: 'Reject', fulfill: 'Fulfill', fulfilled: 'Fulfilled', inventory: 'Inventory', searchMedicines: 'Search medicines...', addItem: 'Add Item', noInventory: 'No inventory items. Add your first item to get started.', distance: 'Distance', requestAccepted: 'Request accepted', requestRejected: 'Request rejected', requestFulfilled: 'Request fulfilled',
  // Blood Test Centre
  diagnosticDashboard: 'Diagnostic Centre Dashboard', manageBookings: 'Manage blood test bookings', totalBookings: 'Total Bookings', pending: 'Pending', accepted: 'Accepted', completed: 'Completed', completedTests: 'Completed Tests', bookingRequests: 'Booking Requests', noBookings: 'No bookings yet.', complete: 'Complete', done: 'Done', bookingUpdated: 'Booking Updated', statusChanged: 'Status changed to', userName: 'User Name', testTypeCol: 'Test Type', requestedDate: 'Requested Date', time: 'Time', notes: 'Notes',
  // Hospital
  hospitalDashboard: 'Hospital Dashboard', manageInventoryAdherence: 'Manage inventory and patient adherence', addMedicineScan: 'Add Medicine (Scan/Manual)', medicineInventory: 'Medicine Inventory', noInventoryYet: 'No inventory items yet. Add your first medicine.', patientAdherence: 'Patient Adherence',
  // Location
  locationRequested: 'Location access requested', locationDenied: 'Location access denied. Request will be sent to all providers.', restockSent: 'Restock Request Sent', restockDesc: 'sent to nearby pharmacies.', requestFor: 'Request for', openMap: 'Open in Maps', viewLocation: 'View Location', noLocation: 'No location', location: 'Location', saveLocation: 'Save My Location', locationSaved: 'Location saved successfully',
  // Offer system
  sendOffer: 'Send Offer', sendRestockOffer: 'Send Restock Offer', sendTestOffer: 'Send Test Offer', price: 'Price', discount: 'Discount', finalPrice: 'Final Price', estimatedTime: 'Estimated Time', estimatedTimePlaceholder: 'e.g. 30 minutes, 2 hours', offerNotesPlaceholder: 'Any additional details...', offerSent: 'Offer Sent', offersSent: 'Offers Sent', offersReceived: 'Offers Received', newOffer: 'New Offer', acceptOffer: 'Accept', rejectOffer: 'Reject', offerAccepted: 'Offer Accepted', offerRejected: 'Offer Rejected', from: 'From', provider: 'Provider', diagnosticCentre: 'Diagnostic Centre', pharmacy: 'Pharmacy', processing: 'Processing', rejected: 'Rejected', orderTracking: 'Tracking', statusUpdated: 'Status Updated',
  // Status
  safe: 'Safe', expiring: 'Expiring',
  // Index
  heroTitle: 'Your Complete Medicine Tracking Platform', heroSubtitle: 'Track medications, manage inventory, book blood tests, and stay on top of your health with MediVault.', getStarted: 'Get Started', learnMore: 'Learn More', features: 'Features', about: 'About', contact: 'Contact',

  // Doctor/HMS enhancements
  doctorDashboard: 'Doctor Dashboard',
  myPatients: 'My Patients',
  reportAnalysis: 'Medical Report Analysis',
  manageDoctors: 'Manage Doctors',
  addDoctor: 'Add Doctor',
  editDoctor: 'Edit Doctor',
  deleteDoctor: 'Delete Doctor',
  resetPassword: 'Reset Password',
  activateDoctor: 'Activate Doctor',
  deactivateDoctor: 'Deactivate Doctor',
  assignPatients: 'Assign Patients',
  doctorName: 'Doctor Name',
  doctorId: 'Doctor ID',
  department: 'Department',
  specialization: 'Specialization',
  employeeId: 'Employee ID',
  overallAdherence: 'Overall Adherence',
  patientName: 'Patient Name',
  patientId: 'Patient ID',
  age: 'Age',
  gender: 'Gender',
  assignedDate: 'Assigned Date',
  currentDiagnosis: 'Current Diagnosis',
  adherenceScoreText: 'Adherence Score',
  totalDoctors: 'Total Doctors',
  totalPatients: 'Total Patients',
  averageAdherence: 'Average Adherence',
  criticalPatients: 'Critical Patients',
  todayUploads: 'Today\'s Report Uploads',
  lowAdherencePatients: 'Patients with Low Adherence',
  medicineExpiryAlerts: 'Medicine Expiry Alerts',
  inventorySummary: 'Inventory Summary',
  patientProfile: 'Patient Profile',
  dailyConsumption: 'Daily Consumption',
  missedDoses: 'Missed Doses',
  skippedMedicines: 'Skipped Medicines',
  weeklyAdherence: 'Weekly Adherence',
  monthlyAdherence: 'Monthly Adherence',
  medicineTimeline: 'Medicine Consumption Timeline',
  doctorNotes: 'Doctor Notes',
  reportSummary: 'Report Summary',
  normalValues: 'Normal Values',
  abnormalValues: 'Abnormal Values',
  criticalValues: 'Critical Values',
  explanationOfAbnormal: 'Explanation of Abnormal Values',
  possibleObservations: 'Possible Observations',
  lifestyleRecs: 'Lifestyle Recommendations',
  suggestedFollowup: 'Suggested Follow-up Tests',
  overallHealthSummary: 'Overall Health Summary',
  aiNotice: 'AI-generated report summary. Final diagnosis should always be made by a qualified medical professional.'
};

const hi: LanguageLabels = {
  ...en,
  dashboard: 'डैशबोर्ड', settings: 'सेटिंग्स', logout: 'लॉग आउट', save: 'सेव करें', cancel: 'रद्द करें', submit: 'जमा करें', loading: 'लोड हो रहा है...', search: 'खोजें', language: 'भाषा', edit: 'संपादित करें', delete: 'हटाएं', active: 'सक्रिय', paused: 'रुका हुआ', notSet: 'सेट नहीं है', verified: 'सत्यापित',
  login: 'लॉग इन', register: 'शुरू करें', signUp: 'साइन अप',
  welcomeBack: 'वापस स्वागत है', totalMedicines: 'कुल दवाइयां', expiringSoon: 'जल्दी समाप्त', expired: 'समाप्त', lowStock: 'कम स्टॉक', quickActions: 'त्वरित कार्य', scanQR: 'QR स्कैन', manualEntry: 'मैन्युअल एंट्री', bookTest: 'टेस्ट बुक करें', addMedicine: 'दवा जोड़ें', myMedicines: 'मेरी दवाइयां', myBloodTestBookings: 'मेरी रक्त परीक्षण बुकिंग', myRestockRequests: 'मेरे रीस्टॉक अनुरोध', confirmed: 'पुष्टि हो गई',
  medicineReminders: 'दवा रिमाइंडर', restockRequests: 'रीस्टॉक अनुरोध', bloodTestBookings: 'रक्त परीक्षण बुकिंग', notifications: 'सूचनाएं', profile: 'प्रोफ़ाइल', personalInfo: 'व्यक्तिगत जानकारी', profileUpdated: 'प्रोफ़ाइल अपडेट हो गई',
  addReminder: 'रिमाइंडर जोड़ें', reminderAdded: 'रिमाइंडर जोड़ा गया', reminderDeleted: 'रिमाइंडर हटाया गया', noReminders: 'कोई रिमाइंडर नहीं। दैनिक दवा सूचनाओं के लिए रिमाइंडर जोड़ें।', reminderTime: 'रिमाइंडर समय', reminder: 'रिमाइंडर', timeToTakeMedicine: 'अपनी दवा लेने का समय',
  markAllRead: 'सभी पढ़ा हुआ', noNotifications: 'अभी कोई सूचना नहीं।',
  activeRequests: 'सक्रिय अनुरोध', completedRequests: 'पूर्ण अनुरोध', noRestockRequests: 'अभी कोई रीस्टॉक अनुरोध नहीं।', activeBookings: 'सक्रिय बुकिंग', completedBookings: 'पूर्ण बुकिंग',
  bookBloodTest: 'रक्त परीक्षण बुक करें', testType: 'परीक्षण प्रकार', selectTestType: 'परीक्षण प्रकार चुनें', preferredDate: 'पसंदीदा तारीख', preferredTime: 'पसंदीदा समय', additionalNotes: 'अतिरिक्त नोट्स', bookingCreated: 'रक्त परीक्षण बुकिंग सफल', bookingDesc: 'आपका अनुरोध डायग्नोस्टिक सेंटरों को भेजा गया।', bookAppointment: 'अपॉइंटमेंट बुक करें', booking: 'बुक हो रहा है...',
  medicineName: 'दवा का नाम', batchNumber: 'बैच नंबर', expiryDate: 'समाप्ति तिथि', quantity: 'मात्रा', dosage: 'खुराक', prescribedDoses: 'निर्धारित खुराक', medicineAdded: 'दवा जोड़ी गई', adherence: 'पालन', takeDose: 'खुराक लें', doseTaken: 'खुराक दर्ज', doseDesc: 'आपका पालन अपडेट किया गया।',
  pharmacyDashboard: 'फार्मेसी डैशबोर्ड', manageInventory: 'अपनी इन्वेंट्री और बिक्री प्रबंधित करें', totalItems: 'कुल आइटम', inventoryValue: 'इन्वेंट्री मूल्य', sellMedicine: 'दवा बेचें', addInventory: 'इन्वेंट्री जोड़ें', csvUpload: 'CSV अपलोड', accept: 'स्वीकार', reject: 'अस्वीकार', fulfill: 'पूरा करें', fulfilled: 'पूरा हुआ', inventory: 'इन्वेंट्री', distance: 'दूरी',
  diagnosticDashboard: 'डायग्नोस्टिक सेंटर डैशबोर्ड', manageBookings: 'रक्त परीक्षण बुकिंग प्रबंधित करें', totalBookings: 'कुल बुकिंग', pending: 'लंबित', accepted: 'स्वीकृत', completed: 'पूर्ण', completedTests: 'पूर्ण परीक्षण', bookingRequests: 'बुकिंग अनुरोध', complete: 'पूरा करें', done: 'हो गया',
  openMap: 'मानचित्र में खोलें', viewLocation: 'स्थान देखें', noLocation: 'स्थान नहीं', location: 'स्थान', saveLocation: 'मेरा स्थान सेव करें', locationSaved: 'स्थान सफलतापूर्वक सेव किया गया',
  sendOffer: 'ऑफर भेजें', sendRestockOffer: 'रीस्टॉक ऑफर भेजें', sendTestOffer: 'टेस्ट ऑफर भेजें', price: 'कीमत', discount: 'छूट', finalPrice: 'अंतिम कीमत', estimatedTime: 'अनुमानित समय', offerSent: 'ऑफर भेजा गया', offersSent: 'ऑफर भेजे गए', offersReceived: 'प्राप्त ऑफर', newOffer: 'नया ऑफर', acceptOffer: 'स्वीकार', rejectOffer: 'अस्वीकार', offerAccepted: 'ऑफर स्वीकृत', offerRejected: 'ऑफर अस्वीकृत', from: 'से', provider: 'प्रदाता', diagnosticCentre: 'डायग्नोस्टिक सेंटर', pharmacy: 'फार्मेसी', processing: 'प्रोसेसिंग', rejected: 'अस्वीकृत', orderTracking: 'ट्रैकिंग', statusUpdated: 'स्थिति अपडेट',
  safe: 'सुरक्षित', expiring: 'समाप्त होने वाला',
  heroTitle: 'आपका संपूर्ण दवा ट्रैकिंग प्लेटफ़ॉर्म', heroSubtitle: 'MediVault के साथ दवाइयों को ट्रैक करें।', getStarted: 'शुरू करें', learnMore: 'और जानें', features: 'सुविधाएं', about: 'परिचय', contact: 'संपर्क',

  doctorDashboard: 'डॉक्टर डैशबोर्ड',
  myPatients: 'मेरे मरीज',
  reportAnalysis: 'मेडिकल रिपोर्ट विश्लेषण',
  manageDoctors: 'डॉक्टरों का प्रबंधन',
  addDoctor: 'डॉक्टर जोड़ें',
  editDoctor: 'डॉक्टर संपादित करें',
  deleteDoctor: 'डॉक्टर हटाएं',
  resetPassword: 'पासवर्ड रीसेट करें',
  activateDoctor: 'डॉक्टर सक्रिय करें',
  deactivateDoctor: 'डॉक्टर निष्क्रिय करें',
  assignPatients: 'मरीज सौंपें',
  doctorName: 'डॉक्टर का नाम',
  doctorId: 'डॉक्टर आईडी',
  department: 'विभाग',
  specialization: 'विशेषज्ञता',
  employeeId: 'कर्मचारी आईडी',
  overallAdherence: 'कुल पालन दर',
  patientName: 'मरीज का नाम',
  patientId: 'मरीज की आईडी',
  age: 'उम्र',
  gender: 'लिंग',
  assignedDate: 'सौंपने की तिथि',
  currentDiagnosis: 'वर्तमान निदान',
  adherenceScoreText: 'पालन स्कोर',
  totalDoctors: 'कुल डॉक्टर',
  totalPatients: 'कुल मरीज',
  averageAdherence: 'औसत पालन दर',
  criticalPatients: 'गंभीर मरीज',
  todayUploads: 'आज के रिपोर्ट अपलोड',
  lowAdherencePatients: 'कम पालन दर वाले मरीज',
  medicineExpiryAlerts: 'दवा समाप्ति अलर्ट',
  inventorySummary: 'इन्वेंट्री सारांश',
  patientProfile: 'मरीज की प्रोफ़ाइल',
  dailyConsumption: 'दैनिक उपभोग',
  missedDoses: 'छूटी हुई खुराकें',
  skippedMedicines: 'छोड़ी गई दवाएं',
  weeklyAdherence: 'साप्ताहिक पालन',
  monthlyAdherence: 'मासिक पालन',
  medicineTimeline: 'दवा उपभोग टाइमलाइन',
  doctorNotes: 'डॉक्टर के नोट्स',
  reportSummary: 'रिपोर्ट सारांश',
  normalValues: 'सामान्य मूल्य',
  abnormalValues: 'असामान्य मूल्य',
  criticalValues: 'गंभीर मूल्य',
  explanationOfAbnormal: 'असामान्य मूल्यों की व्याख्या',
  possibleObservations: 'संभावित अवलोकन',
  lifestyleRecs: 'जीवनशैली की सिफारिशें',
  suggestedFollowup: 'सुझाए गए अनुवर्ती परीक्षण',
  overallHealthSummary: 'समग्र स्वास्थ्य सारांश',
  aiNotice: 'एआई-जनित रिपोर्ट सारांश। अंतिम निदान हमेशा एक योग्य चिकित्सा पेशेवर द्वारा किया जाना चाहिए।'
};

const ur: LanguageLabels = {
  ...en,
  dashboard: 'ڈیش بورڈ', settings: 'ترتیبات', logout: 'لاگ آؤٹ', save: 'محفوظ کریں', cancel: 'منسوخ', submit: 'جمع کریں', loading: 'لوڈ ہو رہا ہے...', search: 'تلاش', language: 'زبان', edit: 'ترمیم', delete: 'حذف', active: 'فعال', paused: 'موقوف', notSet: 'سیٹ نہیں', verified: 'تصدیق شدہ',
  login: 'لاگ ان', register: 'شروع کریں', signUp: 'سائن اپ',
  welcomeBack: 'واپسی پر خوش آمدید', pending: 'زیر التوا', accepted: 'قبول شدہ', completed: 'مکمل', accept: 'قبول', reject: 'مسترد', fulfill: 'پورا کریں', fulfilled: 'پورا ہوا', confirmed: 'تصدیق شدہ',
  medicineReminders: 'دوائی یاد دہانی', restockRequests: 'ری اسٹاک درخواستیں', bloodTestBookings: 'خون کے ٹیسٹ بکنگ', notifications: 'اطلاعات', profile: 'پروفائل', personalInfo: 'ذاتی معلومات', profileUpdated: 'پروفائل اپڈیٹ',
  addReminder: 'یاد دہانی شامل کریں', reminderAdded: 'یاد دہانی شامل', reminderDeleted: 'یاد دہانی حذف', noReminders: 'کوئی یاد دہانی نہیں۔', reminderTime: 'یاد دہانی کا وقت', reminder: 'یاد دہانی', timeToTakeMedicine: 'دوائی لینے کا وقت',
  markAllRead: 'سب پڑھا ہوا', noNotifications: 'ابھی کوئی اطلاع نہیں۔',
  activeRequests: 'فعال درخواستیں', completedRequests: 'مکمل درخواستیں', noRestockRequests: 'کوئی درخواست نہیں۔', activeBookings: 'فعال بکنگ', completedBookings: 'مکمل بکنگ',
  viewLocation: 'مقام دیکھیں', openMap: 'نقشہ میں کھولیں', noLocation: 'مقام نہیں', location: 'مقام', saveLocation: 'میرا مقام محفوظ کریں', locationSaved: 'مقام محفوظ ہو گیا',
  sendOffer: 'آفر بھیجیں', price: 'قیمت', discount: 'رعایت', finalPrice: 'حتمی قیمت', estimatedTime: 'تخمینی وقت', offerSent: 'آفر بھیجا گیا', offersReceived: 'موصول آفرز', newOffer: 'نیا آفر', acceptOffer: 'قبول', rejectOffer: 'مسترد', offerAccepted: 'آفر قبول', offerRejected: 'آفر مسترد', from: 'سے', processing: 'پروسیسنگ', rejected: 'مسترد شدہ', orderTracking: 'ٹریکنگ', statusUpdated: 'حالت اپڈیٹ',
  safe: 'محفوظ', expiring: 'ختم ہونے والا',

  doctorDashboard: 'ڈاکٹر ڈیش بورڈ',
  myPatients: 'میرے مریض',
  reportAnalysis: 'طبی رپورٹ کا تجزیہ',
  manageDoctors: 'ڈاکٹروں کا انتظام',
  addDoctor: 'ڈاکٹر شامل کریں',
  editDoctor: 'ڈاکٹر کی ترمیم',
  deleteDoctor: 'ڈاکٹر کو حذف کریں',
  resetPassword: 'پاس ورڈ دوبارہ ترتیب دیں',
  assignPatients: 'مریض تفویض کریں',
  doctorName: 'ڈاکٹر کا نام',
  doctorId: 'ڈاکٹر کی آئی ڈی',
  department: 'شعبہ',
  specialization: 'تخصص',
  employeeId: 'ملازم کا شناختی کارڈ',
  overallAdherence: 'مجموعی وابستگی',
  patientName: 'مریض کا نام',
  patientId: 'مریض کی آئی ڈی',
  age: 'عمر',
  gender: 'جنس',
  assignedDate: 'تفویض کی تاریخ',
  currentDiagnosis: 'موجودہ تشخیص',
  adherenceScoreText: 'وابستگی کا اسکور',
  totalDoctors: 'کل ڈاکٹرز',
  totalPatients: 'کل مریض',
  averageAdherence: 'اوسط وابستگی',
  criticalPatients: 'سنگین مریض',
  todayUploads: 'آج کے اپ لوڈز',
  lowAdherencePatients: 'کم وابستگی والے مریض',
  medicineExpiryAlerts: 'دوائی کے زائد المیعاد ہونے کے الرٹ',
  inventorySummary: 'انوینٹری کا خلاصہ',
  patientProfile: 'مریض کا پروفائل',
  dailyConsumption: 'روزانہ کا استعمال',
  missedDoses: 'چھوٹی ہوئی خوراکیں',
  skippedMedicines: 'چھوڑی ہوئی دوائیں',
  weeklyAdherence: 'ہفتہ وار وابستگی',
  monthlyAdherence: 'ماہانہ وابستگی',
  medicineTimeline: 'دوائی کے استعمال کی ٹائم لائن',
  doctorNotes: 'ڈاکٹر کے نوٹ',
  reportSummary: 'رپورٹ کا خلاصہ',
  normalValues: 'نارمل اقدار',
  abnormalValues: 'غیر معمولی اقدار',
  criticalValues: 'خطرناک اقدار',
  explanationOfAbnormal: 'غیر معمولی اقدار کی وضاحت',
  possibleObservations: 'ممکنہ مشاہدات',
  lifestyleRecs: 'طرز زندگی کی سفارشات',
  suggestedFollowup: 'تجویز کردہ فالو اپ ٹیسٹ',
  overallHealthSummary: 'مجموعی صحت کا خلاصہ',
  aiNotice: 'مصنوعی ذہانت (AI) سے تیار کردہ رپورٹ کا خلاصہ۔ حتمی تشخیص ہمیشہ ایک قابل ڈاکٹر کو کرنی چاہئے۔'
};

const te: LanguageLabels = {
  ...en,
  dashboard: 'డ్యాష్‌బోర్డ్', settings: 'సెట్టింగ్‌లు', logout: 'లాగ్ అవుట్', save: 'సేవ్', cancel: 'రద్దు', submit: 'సమర్పించు', loading: 'లోడ్ అవుతోంది...', search: 'శోధన', language: 'భాష', edit: 'సవరించు', delete: 'తొలగించు', active: 'సక్రియం', paused: 'ఆపబడింది', notSet: 'సెట్ చేయలేదు', verified: 'ధృవీకరించబడింది',
  login: 'లాగిన్', register: 'ప్రారంభించండి', signUp: 'సైన్ అప్',
  welcomeBack: 'తిరిగి స్వాగతం', pending: 'పెండింగ్', accepted: 'ఆమోదించబడింది', completed: 'పూర్తయింది', accept: 'ఆమోదించు', reject: 'తిరస్కరించు', fulfill: 'పూర్తి చేయి', fulfilled: 'పూర్తయింది', confirmed: 'నిర్ధారించబడింది',
  medicineReminders: 'మందు రిమైండర్లు', restockRequests: 'రీస్టాక్ అభ్యర్థనలు', bloodTestBookings: 'రక బుకింగ్‌లు', notifications: 'నోటిఫికేషన్లు', profile: 'ప్రొఫైల్', personalInfo: 'వ్యక్తిగత సమాచారం', profileUpdated: 'ప్రొఫైల్ నవీకరించబడింది',
  addReminder: 'రిమైండర్ జోడించండి', reminderAdded: 'రిమైండర్ జోడించబడింది', reminderDeleted: 'రిమైండర్ తొలగించబడింది', noReminders: 'రిమైండర్లు లేవు.', reminderTime: 'రిమైండర్ సమయం', reminder: 'రిమైండర్', timeToTakeMedicine: 'మందు తీసుకునే సమయం',
  markAllRead: 'అన్నీ చదివినట్లు', noNotifications: 'నోటిఫికేషన్లు లేవు.',
  activeRequests: 'సక్రియ అభ్యర్థనలు', completedRequests: 'పూర్తయిన అభ్యర్థనలు', noRestockRequests: 'అభ్యర్థనలు లేవు.', activeBookings: 'సక్రియ బుకింగ్‌లు', completedBookings: 'పూర్తయిన బుకింగ్‌లు',
  viewLocation: 'స్థానం చూడండి', openMap: 'మ్యాప్‌లో తెరవండి', noLocation: 'స్థానం లేదు', location: 'స్థానం', saveLocation: 'నా స్థానం సేవ్ చేయండి', locationSaved: 'స్థానం విజయవంతంగా సేవ్ చేయబడింది',
  sendOffer: 'ఆఫర్ పంపండి', price: 'ధర', discount: 'తగ్గింపు', finalPrice: 'తుది ధర', estimatedTime: 'అంచనా సమయం', offerSent: 'ఆఫర్ పంపబడింది', offersReceived: 'అందుకున్న ఆఫర్లు', newOffer: 'కొత్త ఆఫర్', acceptOffer: 'ఆమోదించు', rejectOffer: 'తిరస్కరించు', offerAccepted: 'ఆఫర్ ఆమోదం', offerRejected: 'ఆఫర్ తిరస్కరణ', from: 'నుండి', processing: 'ప్రాసెసింగ్', rejected: 'తిరస్కరించబడింది', orderTracking: 'ట్రాకింగ్', statusUpdated: 'స్థితి నవీకరణ',
  safe: 'సురక్షితం', expiring: 'గడువు ముగుస్తోంది',

  doctorDashboard: 'డాక్టర్ డాష్‌బోర్డ్',
  myPatients: 'నా రోగులు',
  reportAnalysis: 'మెడికల్ రిపోర్ట్ విశ్లేషణ',
  manageDoctors: 'వైద్యుల నిర్వహణ',
  addDoctor: 'వైద్యుడిని జోడించు',
  editDoctor: 'వైద్యుడిని సవరించు',
  deleteDoctor: 'వైద్యుడిని తొలగించు',
  resetPassword: 'పాస్‌వర్డ్ రీసెట్',
  assignPatients: 'రోగులను కేటాయించండి',
  doctorName: 'వైద్యుడి పేరు',
  doctorId: 'వైద్యుడి ఐడి',
  department: 'విభాగం',
  specialization: 'ప్రత్యేకత',
  employeeId: 'ఉద్యోగి ఐడి',
  overallAdherence: 'మొత్తం మందుల వినియోగ రేటు',
  patientName: 'రోగి పేరు',
  patientId: 'రోగి ఐడి',
  age: 'వయస్సు',
  gender: 'లింగం',
  assignedDate: 'కేటాయించిన తేదీ',
  currentDiagnosis: 'ప్రస్తుత రోగ నిర్ధారణ',
  adherenceScoreText: 'వినియోగ స్కోరు',
  totalDoctors: 'మొత్తం వైద్యులు',
  totalPatients: 'మొత్తం రోగులు',
  averageAdherence: 'సగటు వినియోగ రేటు',
  criticalPatients: 'తీవ్ర అనారోగ్య రోగులు',
  todayUploads: 'ఈ రోజు రిపోర్ట్ అప్‌లోడ్‌లు',
  lowAdherencePatients: 'తక్కువ వినియోగ రేటు ఉన్న రోగులు',
  medicineExpiryAlerts: 'మందుల గడువు ముగింపు హెచ్చరికలు',
  inventorySummary: 'ఇన్వెంటరీ సారాంశం',
  patientProfile: 'రోగి ప్రొఫైల్',
  dailyConsumption: 'రోజువారీ వినియోగం',
  missedDoses: 'మరచిపోయిన మోతాదులు',
  skippedMedicines: 'తప్పించుకున్న మందులు',
  weeklyAdherence: 'వారపు వినియోగం',
  monthlyAdherence: 'నెలవారీ వినియోగం',
  medicineTimeline: 'మందుల వినియోగ టైమ్‌లైన్',
  doctorNotes: 'డాక్టర్ నోట్స్',
  reportSummary: 'రిపోర్ట్ సారాంశం',
  normalValues: 'సాధారణ విలువలు',
  abnormalValues: 'అసాధారణ విలువలు',
  criticalValues: 'తీవ్రమైన విలువలు',
  explanationOfAbnormal: 'అసాధారణ విలువల వివరణ',
  possibleObservations: 'సంభావ్య పరిశీలనలు',
  lifestyleRecs: 'జీవనశైలి సిఫార్సులు',
  suggestedFollowup: 'సూచించిన తదుపరి పరీక్షలు',
  overallHealthSummary: 'మొత్తం ఆరోగ్య సారాంశం',
  aiNotice: 'AI ద్వారా సృష్టించబడిన నివేదిక సారాంశం. తుది నిర్ధారణ ఎల్లప్పుడూ అర్హత కలిగిన వైద్యుని ద్వారానే జరగాలి.'
};

const kn: LanguageLabels = {
  ...en,
  dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು', logout: 'ಲಾಗ್ ಔಟ್', save: 'ಉಳಿಸಿ', cancel: 'ರದ್ದು', submit: 'ಸಲ್ಲಿಸಿ', loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...', search: 'ಹುಡುಕಿ', language: 'ಭಾಷೆ', edit: 'ಸಂಪಾದಿಸಿ', delete: 'ಅಳಿಸಿ', active: 'ಸಕ್ರಿಯ', paused: 'ವಿರಾಮ', notSet: 'ಹೊಂದಿಸಿಲ್ಲ', verified: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
  login: 'ಲಾಗಿನ್', register: 'ಪ್ರಾರಂಭಿಸಿ', signUp: 'ಸೈನ್ ಅಪ್',
  welcomeBack: 'ಮರಳಿ ಸ್ವಾಗತ', pending: 'ಬಾಕಿ', accepted: 'ಸ್ವೀಕೃತ', completed: 'ಪೂರ್ಣ', accept: 'ಸ್ವೀಕರಿಸಿ', reject: 'ತಿರಸ್ಕರಿಸಿ', fulfill: 'ಪೂರ್ಣಗೊಳಿಸಿ', fulfilled: 'ಪೂರ್ಣವಾಗಿದೆ', confirmed: 'ದೃಢೀಕರಿಸಲಾಗಿದೆ',
  medicineReminders: 'ಔಷಧ ಜ್ಞಾಪನೆಗಳು', restockRequests: 'ರೀಸ್ಟಾಕ್ ವಿನಂತಿಗಳು', bloodTestBookings: 'ರಕ್ತ ಪರೀಕ್ಷೆ ಬುಕಿಂಗ್‌ಗಳು', notifications: 'ಅಧಿಸೂಚನೆಗಳು', profile: 'ಪ್ರೊಫೈಲ್', personalInfo: 'ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ', profileUpdated: 'ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಲಾಗಿದೆ',
  addReminder: 'ಜ್ಞಾಪನೆ ಸೇರಿಸಿ', reminderAdded: 'ಜ್ಞಾಪನೆ ಸೇರಿಸಲಾಗಿದೆ', reminderDeleted: 'ಜ್ಞಾಪನೆ ಅಳಿಸಲಾಗಿದೆ', noReminders: 'ಜ್ಞಾಪನೆಗಳಿಲ್ಲ.', reminderTime: 'ಜ್ಞಾಪನೆ ಸಮಯ', reminder: 'ಜ್ಞಾಪನೆ', timeToTakeMedicine: 'ಔಷಧ ತೆಗೆದುಕೊಳ್ಳುವ ಸಮಯ',
  markAllRead: 'ಎಲ್ಲಾ ಓದಿದ', noNotifications: 'ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ.',
  activeRequests: 'ಸಕ್ರಿಯ ವಿನಂತಿಗಳು', completedRequests: 'ಪೂರ್ಣಗೊಂಡ ವಿನಂತಿಗಳು', noRestockRequests: 'ವಿನಂತಿಗಳಿಲ್ಲ.', activeBookings: 'ಸಕ್ರಿಯ ಬುಕಿಂಗ್‌ಗಳು', completedBookings: 'ಪೂರ್ಣಗೊಂಡ ಬುಕಿಂಗ್‌ಗಳು',
  viewLocation: 'ಸ್ಥಳ ನೋಡಿ', openMap: 'ನಕ್ಷೆಯಲ್ಲಿ ತೆರೆಯಿರಿ', noLocation: 'ಸ್ಥಳ ಇಲ್ಲ', location: 'ಸ್ಥಳ', saveLocation: 'ನನ್ನ ಸ್ಥಳ ಉಳಿಸಿ', locationSaved: 'ಸ್ಥಳ ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ',
  sendOffer: 'ಆಫರ್ ಕಳುಹಿಸಿ', price: 'ಬೆಲೆ', discount: 'ರಿಯಾಯಿತಿ', finalPrice: 'ಅಂತಿಮ ಬೆಲೆ', estimatedTime: 'ಅಂದಾಜು ಸಮಯ', offerSent: 'ಆಫರ್ ಕಳುಹಿಸಲಾಗಿದೆ', offersReceived: 'ಸ್ವೀಕರಿಸಿದ ಆಫರ್‌ಗಳು', newOffer: 'ಹೊಸ ಆಫರ್', acceptOffer: 'ಸ್ವೀಕರಿಸಿ', rejectOffer: 'ತಿರಸ್ಕರಿಸಿ', offerAccepted: 'ಆಫರ್ ಸ್ವೀಕೃತ', offerRejected: 'ಆಫರ್ ತಿರಸ್ಕಾರ', from: 'ಇಂದ', processing: 'ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿ', rejected: 'ತಿರಸ್ಕೃತ', orderTracking: 'ಟ್ರ್ಯಾಕಿಂಗ್', statusUpdated: 'ಸ್ಥಿತಿ ನವೀಕರಣ',
  safe: 'ಸುರಕ್ಷಿತ', expiring: 'ಮುಕ್ತಾಯ ಹತ್ತಿರ',

  doctorDashboard: 'ವೈದ್ಯರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
  myPatients: 'ನನ್ನ ರೋಗಿಗಳು',
  reportAnalysis: 'ವೈದ್ಯಕೀಯ ವರದಿ ವಿಶ್ಲೇಷಣೆ',
  manageDoctors: 'ವೈದ್ಯರ ನಿರ್ವಹಣೆ',
  addDoctor: 'ವೈದ್ಯರನ್ನು ಸೇರಿಸಿ',
  editDoctor: 'ವೈದ್ಯರನ್ನು ಸಂಪಾದಿಸಿ',
  deleteDoctor: 'ವೈದ್ಯರನ್ನು ಅಳಿಸಿ',
  resetPassword: 'ಪಾಸ್‌ವರ್ಡ್ ಮರುಹೊಂದಿಸಿ',
  assignPatients: 'ರೋಗಿಗಳನ್ನು ನಿಯೋಜಿಸಿ',
  doctorName: 'ವೈದ್ಯರ ಹೆಸರು',
  doctorId: 'ವೈದ್ಯರ ಐಡಿ',
  department: 'ವಿಭಾಗ',
  specialization: 'ವಿಶೇಷತೆ',
  employeeId: 'ನೌಕರರ ಐಡಿ',
  overallAdherence: 'ಒಟ್ಟಾರೆ ಔಷಧ ಸೇವನೆ ಪ್ರಮಾಣ',
  patientName: 'ರೋಗಿಯ ಹೆಸರು',
  patientId: 'ರೋಗಿಯ ಐಡಿ',
  age: 'ವಯಸ್ಸು',
  gender: 'ಲಿಂಗ',
  assignedDate: 'ನಿಯೋಜಿತ ದಿನಾಂಕ',
  currentDiagnosis: 'ಪ್ರಸ್ತುತ ರೋಗನಿರ್ಣಯ',
  adherenceScoreText: 'ಅನುಸರಣೆ ಸ್ಕೋರ್',
  totalDoctors: 'ಒಟ್ಟು ವೈದ್ಯರು',
  totalPatients: 'ಒಟ್ಟು ರೋಗಿಗಳು',
  averageAdherence: 'ಸರಾಸರಿ ಅನುಸರಣೆ',
  criticalPatients: 'ಅಪಾಯದಲ್ಲಿರುವ ರೋಗಿಗಳು',
  todayUploads: 'ಇಂದಿನ ವರದಿ ಅಪ್‌ಲೋಡ್‌ಗಳು',
  lowAdherencePatients: 'ಕಡಿಮೆ ಅನುಸರಣೆ ಇರುವ ರೋಗಿಗಳು',
  medicineExpiryAlerts: 'ಔಷಧ ಮುಕ್ತಾಯದ ಎಚ್ಚರಿಕೆಗಳು',
  inventorySummary: 'ದಾಸ್ತಾನು ಸಾರಾಂಶ',
  patientProfile: 'ರೋಗಿಯ ಪ್ರೊಫೈಲ್',
  dailyConsumption: 'ದೈನಂದಿನ ಬಳಕೆ',
  missedDoses: 'ತಪ್ಪಿದ ಪ್ರಮಾಣಗಳು',
  skippedMedicines: 'ಬಿಟ್ಟ ಔಷಧಗಳು',
  weeklyAdherence: 'ವಾರದ ಅನುಸರಣೆ',
  monthlyAdherence: 'ತಿಂಗಳ ಅನುಸರಣೆ',
  medicineTimeline: 'ಔಷಧ ಸೇವನೆಯ ಟೈಮ್‌ಲೈನ್',
  doctorNotes: 'ವೈದ್ಯರ ಟಿಪ್ಪಣಿಗಳು',
  reportSummary: 'ವರದಿಯ ಸಾರಾಂಶ',
  normalValues: 'ಸಾಮಾನ್ಯ ಮೌಲ್ಯಗಳು',
  abnormalValues: 'ಅಸಹಜ ಮೌಲ್ಯಗಳು',
  criticalValues: 'ನಿರ್ಣಾಯಕ ಮೌಲ್ಯಗಳು',
  explanationOfAbnormal: 'ಅಸಹಜ ಮೌಲ್ಯಗಳ ವಿವರಣೆ',
  possibleObservations: 'ಸಂಭವನೀಯ ಅವಲೋಕನಗಳು',
  lifestyleRecs: 'ಜೀವನಶೈಲಿ ಶಿಫಾರಸುಗಳು',
  suggestedFollowup: 'ಸೂಚಿಸಲಾದ ಅನುಸರಣಾ ಪರೀಕ್ಷೆಗಳು',
  overallHealthSummary: 'ಒಟ್ಟಾರೆ ಆರೋಗ್ಯ ಸಾರಾಂಶ',
  aiNotice: 'AI ಸೃಜಿಸಿದ ವರದಿ ಸಾರಾಂಶ. ಅಂತಿಮ ರೋಗನಿರ್ಣಯವನ್ನು ಯಾವಾಗಲೂ ಅರ್ಹ ವೈದ್ಯರು ಮಾಡಬೇಕು.'
};

const ta: LanguageLabels = {
  ...en,
  dashboard: 'டாஷ்போர்டு', settings: 'அமைப்புகள்', logout: 'வெளியேறு', save: 'சேமி', cancel: 'ரத்துசெய்', submit: 'சமர்ப்பி', loading: 'ஏற்றப்படுகிறது...', search: 'தேடு', language: 'மொழி', edit: 'தொகு', delete: 'அழி', active: 'செயலில்', verified: 'சரிபார்க்கப்பட்டது',
  login: 'உள்நுழை', register: 'தொடங்குங்கள்', signUp: 'பதிவுசெய்',
  welcomeBack: 'நல்வரவு', totalMedicines: 'மொத்த மருந்துகள்', expiringSoon: 'விரைவில் காலாவதியாகும்', expired: 'காலாவதியானது', lowStock: 'குறைந்த இருப்பு', quickActions: 'விரைவு செயல்கள்', scanQR: 'QR ஸ்கேன்', manualEntry: 'கைமுறை பதிவு', bookTest: 'சோதனை பதிவுசெய்', addMedicine: 'மருந்து சேர்', myMedicines: 'எனது மருந்துகள்', myBloodTestBookings: 'எனது இரத்த பரிசோதனைகள்', myRestockRequests: 'எனது இருப்பு கோரிக்கைகள்', confirmed: 'உறுதி செய்யப்பட்டது',
  medicineReminders: 'மருந்து நினைவூட்டல்கள்', restockRequests: 'இருப்பு கோரிக்கைகள்', bloodTestBookings: 'இரத்த பரிசோதனை பதிவுகள்', notifications: 'அறிவிப்புகள்', profile: 'சுயவிவரம்', personalInfo: 'தனிப்பட்ட தகவல்', profileUpdated: 'சுயவிவரம் புதுப்பிக்கப்பட்டது',
  addReminder: 'நினைவூட்டல் சேர்', reminderAdded: 'நினைவூட்டல் சேர்க்கப்பட்டது', reminderDeleted: 'நினைவூட்டல் நீக்கப்பட்டது', reminderTime: 'நினைவூட்டல் நேரம்', reminder: 'நினைவூட்டல்', timeToTakeMedicine: 'மருந்து உட்கொள்ளும் நேரம்',
  markAllRead: 'அனைத்தையும் படித்ததாக குறி', noNotifications: 'அறிவிப்புகள் எதுவும் இல்லை.',
  activeRequests: 'செயலில் உள்ள கோரிக்கைகள்', completedRequests: 'முடிவடைந்த கோரிக்கைகள்',
  bookBloodTest: 'இரத்த பரிசோதனை பதிவுசெய்', testType: 'பரிசோதனை வகை', selectTestType: 'பரிசோதனை வகையைத் தேர்ந்தெடுக்கவும்', preferredDate: 'விருப்பமான தேதி', preferredTime: 'விருப்பமான நேரம்', additionalNotes: 'கூடுதல் குறிப்புகள்', bookingCreated: 'இரத்த பரிசோதனை பதிவு வெற்றிகரமாக முடிந்தது', bookAppointment: 'முன்பதிவு செய்',
  medicineName: 'மருந்தின் பெயர்', batchNumber: 'தொகுதி எண்', expiryDate: 'காலாவதி தேதி', quantity: 'அளவு', dosage: 'அளவு முறை', prescribedDoses: 'பரிந்துரைக்கப்பட்ட அளவுகள்', medicineAdded: 'மருந்து சேர்க்கப்பட்டது', adherence: 'மருந்து உட்கொள்ளல்', takeDose: 'மருந்து உட்கொள்', doseTaken: 'மருந்து உட்கொள்ளப்பட்டது',
  pharmacyDashboard: 'மருந்தக டாஷ்போர்டு', manageInventory: 'இருப்பு மற்றும் விற்பனையை நிர்வகி', totalItems: 'மொத்த பொருட்கள்', sellMedicine: 'மருந்து விற்பனை செய்', addInventory: 'இருப்பைச் சேர்', csvUpload: 'CSV பதிவேற்றம்', accept: 'ஏற்றுக்கொள்', reject: 'நிராகரி', fulfill: 'நிறைவேற்று', fulfilled: 'நிறைவேற்றப்பட்டது', inventory: 'இருப்பு',
  diagnosticDashboard: 'பரிசோதனை மைய டாஷ்போர்டு', manageBookings: 'சோதனை பதிவுகளை நிர்வகி', totalBookings: 'மொத்த பதிவுகள்', pending: 'நிலுவையில் உள்ளவை', accepted: 'ஏற்கப்பட்டவை', completed: 'முடிவடைந்தவை', bookingRequests: 'முன்பதிவு கோரிக்கைகள்', complete: 'முடித்தல்', done: 'முடிந்தது',
  openMap: 'வரைபடத்தில் திற', viewLocation: 'இருப்பிடத்தைக் காட்டு', location: 'இருப்பிடம்', saveLocation: 'இருப்பிடத்தைச் சேமி', locationSaved: 'இருப்பிடம் வெற்றிகரமாக சேமிக்கப்பட்டது',
  price: 'விலை', discount: 'தள்ளுபடி', finalPrice: 'இறுதி விலை', estimatedTime: 'மதிப்பிடப்பட்ட நேரம்', offerSent: 'சலுகை அனுப்பப்பட்டது', offersReceived: 'பெறப்பட்ட சலுகைகள்', newOffer: 'புதிய சலுகை', acceptOffer: 'ஏற்றுக்கொள்', rejectOffer: 'நிராகரி',
  safe: 'பாதுகாப்பானது', expiring: 'காலாவதியாகிறது',

  doctorDashboard: 'மருத்துவர் டாஷ்போர்டு',
  myPatients: 'எனது நோயாளிகள்',
  reportAnalysis: 'மருத்துவ அறிக்கை பகுப்பாய்வு',
  manageDoctors: 'மருத்துவர்கள் மேலாண்மை',
  addDoctor: 'மருத்துவர் சேர்',
  editDoctor: 'மருத்துவர் விவரம் திருத்து',
  deleteDoctor: 'மருத்துவர் நீக்கு',
  resetPassword: 'கடவுச்சொல்லை மீட்டமை',
  assignPatients: 'நோயாளிகளை ஒதுக்கீடு செய்',
  doctorName: 'மருத்துவர் பெயர்',
  doctorId: 'மருத்துவர் ஐடி',
  department: 'துறை',
  specialization: 'சிறப்புத் துறை',
  employeeId: 'பணியாளர் ஐடி',
  overallAdherence: 'ஒட்டுமொத்த மருந்து உட்கொள்ளல் விகிதம்',
  patientName: 'நோயாளி பெயர்',
  patientId: 'நோயாளி ஐடி',
  age: 'வயது',
  gender: 'பாலினம்',
  assignedDate: 'ஒதுக்கப்பட்ட தேதி',
  currentDiagnosis: 'தற்போதைய நோய் கண்டறிதல்',
  adherenceScoreText: 'உட்கொள்ளல் குறியீடு',
  totalDoctors: 'மொத்த மருத்துவர்கள்',
  totalPatients: 'மொத்த நோயாளிகள்',
  averageAdherence: 'சராசரி உட்கொள்ளல்',
  criticalPatients: 'அபாய கட்ட நோயாளிகள்',
  todayUploads: 'இன்றைய அறிக்கை பதிவேற்றங்கள்',
  lowAdherencePatients: 'குறைந்த உட்கொள்ளல் நோயாளிகள்',
  medicineExpiryAlerts: 'மருந்து காலாவதி அறிவிப்புகள்',
  inventorySummary: 'இருப்புச் சுருக்கம்',
  patientProfile: 'நோயாளி சுயவிவரம்',
  dailyConsumption: 'தினசரி உட்கொள்ளல்',
  missedDoses: 'தவறவிட்ட அளவுகள்',
  skippedMedicines: 'தவிர்த்த மருந்துகள்',
  weeklyAdherence: 'வாராந்திர உட்கொள்ளல்',
  monthlyAdherence: 'மாதாந்திர உட்கொள்ளல்',
  medicineTimeline: 'மருந்து உட்கொள்ளல் காலவரிசை',
  doctorNotes: 'மருத்துவரின் குறிப்புகள்',
  reportSummary: 'அறிக்கை சுருக்கம்',
  normalValues: 'சாதாரண மதிப்புகள்',
  abnormalValues: 'அசாதாரண மதிப்புகள்',
  criticalValues: 'முக்கிய மதிப்புகள்',
  explanationOfAbnormal: 'அசாதாரண மதிப்புகளின் விளக்கம்',
  possibleObservations: 'சாத்தியமான அவதானிப்புகள்',
  lifestyleRecs: 'வாழ்க்கை முறை பரிந்துரைகள்',
  suggestedFollowup: 'பரிந்துரைக்கப்படும் தொடர் சோதனைகள்',
  overallHealthSummary: 'ஒட்டுமொத்த சுகாதார சுருக்கம்',
  aiNotice: 'செயற்கை நுண்ணறிவு (AI) மூலம் தயாரிக்கப்பட்ட அறிக்கை சுருக்கம். இறுதி நோயறிதல் எப்போதும் தகுதிவாய்ந்த மருத்துவ நிபுணரால் செய்யப்பட வேண்டும்.'
};

const ml: LanguageLabels = {
  ...en,
  dashboard: 'ഡാഷ്‌ബോർഡ്', settings: 'ക്രമീകരണങ്ങൾ', logout: 'ലോഗ് ഔട്ട്', save: 'സൂക്ഷിക്കുക', cancel: 'റദ്ദാക്കുക', submit: 'സമർപ്പിക്കുക', loading: 'ലോഡുചെയ്യുന്നു...', search: 'തിരയുക', language: 'ഭാഷ', edit: 'തിരുത്തുക', delete: 'ഇല്ലാതാക്കുക', active: 'സജീവം', verified: 'സ്ഥിരീകരിച്ചു',
  login: 'ലോഗിൻ', register: 'ആരംഭിക്കുക', signUp: 'സൈൻ അപ്പ്',
  welcomeBack: 'വീണ്ടും സ്വാഗതം', totalMedicines: 'ആകെ മരുന്നുകൾ', expiringSoon: 'ഉടൻ കാലാവധി തീരുന്നവ', expired: 'കാലാവധി കഴിഞ്ഞവ', lowStock: 'കുറഞ്ഞ സ്റ്റോക്ക്', quickActions: 'ദ്രുത പ്രവൃത്തികൾ', scanQR: 'ക്യുആർ സ്കാൻ', bookTest: 'ടെസ്റ്റ് ബുക്ക് ചെയ്യുക', addMedicine: 'മരുന്ന് ചേർക്കുക', myMedicines: 'എന്റെ മരുന്നുകൾ', confirmed: 'സ്ഥിരീകരിച്ചു',
  medicineReminders: 'മരുന്ന് ഓർമ്മപ്പെടുത്തലുകൾ', restockRequests: 'റീസ്റ്റോക്ക് അഭ്യർത്ഥനകൾ', bloodTestBookings: 'ബ്ലഡ് ടെസ്റ്റ് ബുക്കിംഗുകൾ', notifications: 'അറിയിപ്പുകൾ', profile: 'പ്രൊഫൈൽ', personalInfo: 'വ്യക്തിഗത വിവരങ്ങൾ', profileUpdated: 'പ്രൊഫൈൽ പുതുക്കി',
  addReminder: 'ഓർമ്മപ്പെടുത്തൽ ചേർക്കുക', reminderAdded: 'ഓർമ്മപ്പെടുത്തൽ ചേർത്തു', reminderDeleted: 'ഓർമ്മപ്പെടുത്തൽ നീക്കംചെയ്തു', reminderTime: 'ഓർമ്മപ്പെടുത്തൽ സമയം', reminder: 'ഓർമ്മപ്പെടുത്തൽ', timeToTakeMedicine: 'മരുന്ന് കഴിക്കേണ്ട സമയം',
  markAllRead: 'എല്ലാം വായിച്ചതായി അടയാളപ്പെടുത്തുക', noNotifications: 'അറിയിപ്പുകൾ ഒന്നുമില്ല.',
  bookBloodTest: 'ബ്ലഡ് ടെസ്റ്റ് ബുക്ക് ചെയ്യുക', testType: 'ടെസ്റ്റ് തരം', selectTestType: 'ടെസ്റ്റ് തരം തിരഞ്ഞെടുക്കുക', preferredDate: 'തീയതി', preferredTime: 'സമയം', bookingCreated: 'ബുക്കിംഗ് വിജയകരമായി പൂർത്തിയായി',
  medicineName: 'മരുന്നിന്റെ പേര്', expiryDate: 'കാലാവധി തീയതി', quantity: 'അളവ്', prescribedDoses: 'നിർദ്ദേശിച്ച അളവ്', medicineAdded: 'മരുന്ന് ചേർത്തു', adherence: 'മരുന്ന് ഉപയോഗക്രമം', takeDose: 'മരുന്ന് കഴിക്കുക', doseTaken: 'മരുന്ന് കഴിച്ചു',
  pharmacyDashboard: 'ഫാർമസി ഡാഷ്‌ബോർഡ്', manageInventory: 'സ്റ്റോക്കും വിൽപ്പനയും കൈകാര്യം ചെയ്യുക', totalItems: 'ആകെ ഇനങ്ങൾ', sellMedicine: 'മരുന്ന് വിൽക്കുക', addInventory: 'സ്റ്റോക്ക് ചേർക്കുക', csvUpload: 'CSV അപ്‌ലോഡ്', accept: 'സ്വീകരിക്കുക', reject: 'നിരസിക്കുക', fulfill: 'പൂർത്തിയാക്കുക', fulfilled: 'പൂർത്തിയാക്കി', inventory: 'സ്റ്റോക്ക്',
  diagnosticDashboard: 'ഡയഗ്നോസ്റ്റിക് സെന്റർ ഡാഷ്‌ബോർഡ്', manageBookings: 'ബുക്കിംഗുകൾ കൈകാര്യം ചെയ്യുക', pending: 'തീർച്ചപ്പെടുത്താത്തവ', accepted: 'സ്വീകരിച്ചവ', completed: 'പൂർത്തിയായവ', bookingRequests: 'ബുക്കിംഗ് അഭ്യർത്ഥനകൾ', complete: 'പൂർത്തിയാക്കുക', done: 'ചെയ്തു കഴിഞ്ഞു',
  openMap: 'മാപ്പിൽ തുറക്കുക', viewLocation: 'സ്ഥലം കാണുക', location: 'സ്ഥലം', saveLocation: 'എന്റെ സ്ഥലം സൂക്ഷിക്കുക', locationSaved: 'സ്ഥലം വിജയകരമായി സൂക്ഷിച്ചു',
  price: 'വില', discount: 'കിഴിവ്', finalPrice: 'അന്തിമ വില', estimatedTime: 'പ്രതീക്ഷിക്കുന്ന സമയം', offerSent: 'ഓഫർ അയച്ചു', offersReceived: 'ലഭിച്ച ഓഫറുകൾ', newOffer: 'പുതിയ ഓഫർ',
  safe: 'സുരക്ഷിതം', expiring: 'കാലാവധി തീരാറായി',

  doctorDashboard: 'ഡോക്ടർ ഡാഷ്‌ബോർഡ്',
  myPatients: 'എന്റെ രോഗികൾ',
  reportAnalysis: 'മെഡിക്കൽ റിപ്പോർട്ട് വിശകലനം',
  manageDoctors: 'ഡോക്ടർമാരെ നിയന്ത്രിക്കുക',
  addDoctor: 'ഡോക്ടറെ ചേർക്കുക',
  editDoctor: 'ഡോക്ടറുടെ വിവരങ്ങൾ തിരുത്തുക',
  deleteDoctor: 'ഡോക്ടറെ നീക്കം ചെയ്യുക',
  resetPassword: 'പാസ്‌വേഡ് പുനഃക്രമീകരിക്കുക',
  assignPatients: 'രോഗികളെ ചുമതലപ്പെടുത്തുക',
  doctorName: 'ഡോക്ടറുടെ പേര്',
  doctorId: 'ഡോക്ടർ ഐഡി',
  department: 'വിഭാഗം',
  specialization: 'വിദഗ്ദ്ധ മേഖല',
  employeeId: 'എംപ്ലോയി ഐഡി',
  overallAdherence: 'മൊത്തത്തിലുള്ള മരുന്ന് ഉപയോഗ നിരക്ക്',
  patientName: 'രോഗിയുടെ പേര്',
  patientId: 'രോഗി ഐഡി',
  age: 'പ്രായം',
  gender: 'ലിംഗം',
  assignedDate: 'ചുമതലപ്പെടുത്തിയ തീയതി',
  currentDiagnosis: 'നിലവിലെ രോഗനിർണയം',
  adherenceScoreText: 'അനുസരണ സ്കോർ',
  totalDoctors: 'ആകെ ഡോക്ടർമാർ',
  totalPatients: 'ആകെ രോഗികൾ',
  averageAdherence: 'ശരാശരി അനുസരണം',
  criticalPatients: 'ഗുരുതരാവസ്ഥയിലുള്ള രോഗികൾ',
  todayUploads: 'ഇന്നത്തെ റിപ്പോർട്ട് അപ്‌ലോഡുകൾ',
  lowAdherencePatients: 'മരുന്ന് ഉപയോഗത്തിൽ വീഴ്ച വരുത്തുന്ന രോഗികൾ',
  medicineExpiryAlerts: 'മരുന്ന് കാലാവധി മുന്നറിയിപ്പുകൾ',
  inventorySummary: 'ഇൻവെന്ററി സംഗ്രഹം',
  patientProfile: 'രോഗിയുടെ പ്രൊഫൈൽ',
  dailyConsumption: 'പ്രതിദിന ഉപഭോഗം',
  missedDoses: 'കഴിക്കാൻ വിട്ടുപോയ അളവ്',
  skippedMedicines: 'കഴിക്കാതെ ഒഴിവാക്കിയ മരുന്നുകൾ',
  weeklyAdherence: 'പ്രതിവാര അനുസരണം',
  monthlyAdherence: 'പ്രതിമാസ അനുസരണം',
  medicineTimeline: 'മരുന്ന് ഉപഭോഗ ടൈംലൈൻ',
  doctorNotes: 'ഡോക്ടറുടെ കുറിപ്പുകൾ',
  reportSummary: 'റിപ്പോർട്ട് സംഗ്രഹം',
  normalValues: 'സാധാരണ അളവ്',
  abnormalValues: 'അസാധാരണ അളവ്',
  criticalValues: 'നിർണ്ണായകമായ അളവ്',
  explanationOfAbnormal: 'അസാധാരണ അളവുകളുടെ വിശദീകരണം',
  possibleObservations: 'സാധ്യമായ നിരീക്ഷണങ്ങൾ',
  lifestyleRecs: 'ജീവിതശൈലി നിർദ്ദേശങ്ങൾ',
  suggestedFollowup: 'നിർദ്ദേശിക്കപ്പെട്ട തുടർ പരിശോധനകൾ',
  overallHealthSummary: 'മൊത്തത്തിലുള്ള ആരോഗ്യ സംഗ്രഹം',
  aiNotice: 'AI നിർമ്മിത റിപ്പോർട്ട് സംഗ്രഹം. അന്തിമ രോഗനിർണ്ണയം എല്ലായ്പ്പോഴും ഒരു യോഗ്യതയുള്ള മെഡിക്കൽ പ്രൊഫഷണൽ മാത്രമേ ചെയ്യാവൂ.'
};

const mr: LanguageLabels = {
  ...en,
  dashboard: 'डॅशबोर्ड', settings: 'सेटिंग्ज', logout: 'लॉग आउट', save: 'सेव्ह', cancel: 'रद्द', submit: 'सबमिट', loading: 'लोड होत आहे...', search: 'शोधा', language: 'भाषा', edit: 'संपादित करा', delete: 'हटवा', active: 'सक्रिय', paused: 'थांबवले', notSet: 'सेट नाही', verified: 'सत्यापित',
  login: 'लॉग इन', register: 'सुरू करा', signUp: 'साइन अप',
  welcomeBack: 'परत स्वागत', pending: 'प्रलंबित', accepted: 'स्वीकृत', completed: 'पूर्ण', accept: 'स्वीकारा', reject: 'नाकारा', fulfill: 'पूर्ण करा', fulfilled: 'पूर्ण झाले', confirmed: 'पुष्टी झाली',
  medicineReminders: 'औषध स्मरणपत्रे', restockRequests: 'रीस्टॉक विनंत्या', bloodTestBookings: 'रक्त तपासणी बुकिंग', notifications: 'सूचना', profile: 'प्रोफाइल', personalInfo: 'वैयक्तिक माहिती', profileUpdated: 'प्रोफाइल अद्यतनित',
  addReminder: 'स्मरणपत्र जोडा', reminderAdded: 'स्मरणपत्र जोडले', reminderDeleted: 'स्मरणपत्र हटवले', noReminders: 'कोणतेही स्मरणपत्र नाही.', reminderTime: 'स्मरणपत्र वेळ', reminder: 'स्मरणपत्र', timeToTakeMedicine: 'औषध घेण्याची वेळ',
  markAllRead: 'सर्व वाचलेले', noNotifications: 'सूचना नाहीत.',
  activeRequests: 'सक्रिय विनंत्या', completedRequests: 'पूर्ण विनंत्या', noRestockRequests: 'विनंत्या नाहीत.', activeBookings: 'सक्रिय बुकिंग', completedBookings: 'पूर्ण बुकिंग',
  viewLocation: 'स्थान पहा', openMap: 'नकाशात उघडा', noLocation: 'स्थान नाही', location: 'स्थान', saveLocation: 'माझे स्थान सेव्ह करा', locationSaved: 'स्थान यशस्वीरित्या सेव्ह झाले',
  sendOffer: 'ऑफर पाठवा', price: 'किंमत', discount: 'सूट', finalPrice: 'अंतिम किंमत', estimatedTime: 'अंदाजे वेळ', offerSent: 'ऑफर पाठवले', offersReceived: 'प्राप्त ऑफर', newOffer: 'नवीन ऑफर', acceptOffer: 'स्वीकारा', rejectOffer: 'नाकारा', offerAccepted: 'ऑफर स्वीकृत', offerRejected: 'ऑफर नाकारले', from: 'कडून', processing: 'प्रोसेसिंग', rejected: 'नाकारले', orderTracking: 'ट्रॅकिंग', statusUpdated: 'स्थिती अद्यतनित',
  safe: 'सुरक्षित', expiring: 'संपत आहे',

  doctorDashboard: 'डॉक्टर डॅशबोर्ड',
  myPatients: 'माझे रुग्ण',
  reportAnalysis: 'वैद्यकीय अहवाल विश्लेषण',
  manageDoctors: 'डॉक्टरांचे व्यवस्थापन',
  addDoctor: 'डॉक्टर जोडा',
  editDoctor: 'डॉक्टर माहिती संपादित करा',
  deleteDoctor: 'डॉक्टर काढा',
  resetPassword: 'पासवर्ड रीसेट करा',
  assignPatients: 'रुग्ण नियुक्त करा',
  doctorName: 'डॉक्टरांचे नाव',
  doctorId: 'डॉक्टर आयडी',
  department: 'विभाग',
  specialization: 'विशेषज्ञता',
  employeeId: 'कर्मचारी आयडी',
  overallAdherence: 'एकूण औषधोपचार पालन दर',
  patientName: 'रुग्णाचे नाव',
  patientId: 'रुग्ण आयडी',
  age: 'वय',
  gender: 'लिंग',
  assignedDate: 'नियुक्त केल्याची तारीख',
  currentDiagnosis: 'सध्याचे निदान',
  adherenceScoreText: 'पालन स्कोअर',
  totalDoctors: 'एकूण डॉक्टर',
  totalPatients: 'एकूण रुग्ण',
  averageAdherence: 'सरासरी पालन दर',
  criticalPatients: 'गंभीर रुग्ण',
  todayUploads: 'आजचे अहवाल अपलोड',
  lowAdherencePatients: 'कमी पालन असलेले रुग्ण',
  medicineExpiryAlerts: 'औषध कालबाह्यता अलर्ट',
  inventorySummary: 'इन्वेंटरी सारांश',
  patientProfile: 'रुग्ण प्रोफाइल',
  dailyConsumption: 'दैनिक वापर',
  missedDoses: 'चुकलेले डोस',
  skippedMedicines: 'टाळलेली औषधे',
  weeklyAdherence: 'साप्ताहिक पालन',
  monthlyAdherence: 'मासिक पालन',
  medicineTimeline: 'औषध वापराची टाइमलाइन',
  doctorNotes: 'डॉक्टरांच्या नोंदी',
  reportSummary: 'अहवाल सारांश',
  normalValues: 'सामान्य मूल्ये',
  abnormalValues: 'असामान्य मूल्ये',
  criticalValues: 'गंभीर मूल्ये',
  explanationOfAbnormal: 'असामान्य मूल्यांचे स्पष्टीकरण',
  possibleObservations: 'संभाव्य निरीक्षणे',
  lifestyleRecs: 'जीवनशैली शिफारसी',
  suggestedFollowup: 'सुचवलेल्या फॉलो-अप चाचण्या',
  overallHealthSummary: 'एकूण आरोग्य सारांश',
  aiNotice: 'AI द्वारे तयार केलेला अहवाल सारांश. अंतिम निदान नेहमी पात्र वैद्यकीय व्यावसायिकानेच केले पाहिजे.'
};

const gu: LanguageLabels = {
  ...en,
  dashboard: 'ડૅશબોર્ડ', settings: 'સેટિંગ્સ', logout: 'લોગ આઉટ', save: 'સાચવો', cancel: 'રદ કરો', submit: 'સબમિટ કરો', loading: 'લોડ થઈ રહ્યું છે...', search: 'શોધો', language: 'ભાષા', edit: 'ફેરફાર કરો', delete: 'કાઢી નાખો', active: 'સક્રિય', verified: 'વેરિફાઇડ',
  login: 'લોગ ઇન', register: 'શરૂ કરો', signUp: 'સાઇન અપ',
  welcomeBack: 'આપનું સ્વાગત છે', totalMedicines: 'કુલ દવાઓ', expiringSoon: 'ટૂંક સમયમાં સમાપ્ત થતી', expired: 'સમાપ્ત થયેલ', lowStock: 'ઓછો સ્ટોક', quickActions: 'ઝડપી કાર્યો', scanQR: 'QR સ્કેન', bookTest: 'ટેસ્ટ બુક કરો', addMedicine: 'દવા ઉમેરો', myMedicines: 'મારી દવાઓ', confirmed: 'પુષ્ટિ થયેલ',
  medicineReminders: 'દવા રીમાઇન્ડર્સ', restockRequests: 'રીસ્ટોક વિનંતીઓ', bloodTestBookings: 'બ્લડ ટેસ્ટ બુકિંગ', notifications: 'સૂચનાઓ', profile: 'પ્રોફાઇલ', personalInfo: 'વ્યક્તિગત માહિતી', profileUpdated: 'પ્રોફાઇલ અપડેટ થઈ ગઈ',
  addReminder: 'રીમાઇન્ડર ઉમેરો', reminderAdded: 'રીમાઇન્ડર ઉમેરાયું', reminderDeleted: 'રીમાઇન્ડર રદ કરાયું', reminderTime: 'રીમાઇન્ડર સમય', reminder: 'રીમાઇન્ડર', timeToTakeMedicine: 'દવા લેવાનો સમય',
  markAllRead: 'બધા વાંચેલા તરીકે ચિહ્નિત કરો', noNotifications: 'કોઈ સૂચના નથી.',
  bookBloodTest: 'બ્લડ ટેસ્ટ બુક કરો', testType: 'ટેસ્ટ પ્રકાર', selectTestType: 'ટેસ્ટ પ્રકાર પસંદ કરો', preferredDate: 'તારીખ', preferredTime: 'સમય', bookingCreated: 'બુકિંગ સફળતાપૂર્વક થઈ ગયું',
  medicineName: 'દવાનું નામ', expiryDate: 'સમાપ્તિ તારીખ', quantity: 'જથ્થો', prescribedDoses: 'નિયત ડોઝ', medicineAdded: 'દવા ઉમેરાઈ', adherence: 'દવા લેવાની નિયમિતતા', takeDose: 'ડોઝ લો', doseTaken: 'ડોઝ લેવાઈ ગયો',
  pharmacyDashboard: 'ફાર્મસી ડૅશબોર્ડ', manageInventory: 'ઇન્વેન્ટરી અને વેચાણ સંચાલન', totalItems: 'કુલ વસ્તુઓ', sellMedicine: 'દવા વેચો', addInventory: 'ઇન્વેન્ટરી ઉમેરો', csvUpload: 'CSV અપલોડ', accept: 'સ્વીકારો', reject: 'નકારો', fulfill: 'પૂર્ણ કરો', fulfilled: 'પૂર્ણ થયું', inventory: 'ઇન્વેન્ટરી',
  diagnosticDashboard: 'ડાયગ્નોસ્ટિક સેન્ટર ડૅશબોર્ડ', manageBookings: 'બુકિંગ મેનેજ કરો', pending: 'બાકી', accepted: 'સ્વીકૃત', completed: 'પૂર્ણ', bookingRequests: 'બુકિંગ વિનંતીઓ', complete: 'પૂર્ણ કરો', done: 'થઈ ગયું',
  openMap: 'નકશામાં ખોલો', viewLocation: 'સ્થાન જુઓ', location: 'સ્થાન', saveLocation: 'મારું સ્થાન સાચવો', locationSaved: 'સ્થાન સફળતાપૂર્વક સચવાયું',
  price: 'કિંમત', discount: 'વળતર', finalPrice: 'અંતિમ કિંમત', estimatedTime: 'અંદાજિત સમય', offerSent: 'ઓફર મોકલાઈ ગઈ', offersReceived: 'મળેલ ઓફર્સ', newOffer: 'નવી ઓફર',
  safe: 'સુરક્ષિત', expiring: 'સમાપ્ત થવાના આરે',

  doctorDashboard: 'ડોક્ટર ડૅશબોર્ડ',
  myPatients: 'મારા દર્દીઓ',
  reportAnalysis: 'મેડિકલ રિપોર્ટ વિશ્લેષણ',
  manageDoctors: 'ડોક્ટરોનું સંચાલન',
  addDoctor: 'ડોક્ટર ઉમેરો',
  editDoctor: 'ડોક્ટર માહિતી સંપાદિત કરો',
  deleteDoctor: 'ડોક્ટર કાઢી નાખો',
  resetPassword: 'પાસવર્ડ રીસેટ કરો',
  assignPatients: 'દર્દીઓ સોંપો',
  doctorName: 'ડોક્ટરનું નામ',
  doctorId: 'ડોક્ટર આઈડી',
  department: 'વિભાગ',
  specialization: 'વિશેષતા',
  employeeId: 'કર્મચારી આઈડી',
  overallAdherence: 'સમગ્ર દવા પાલન દર',
  patientName: 'દર્દીનું નામ',
  patientId: 'દર્દી આઈડી',
  age: 'ઉંમર',
  gender: 'જાતિ',
  assignedDate: 'સોંપાયેલ તારીખ',
  currentDiagnosis: 'વર્તમાન નિદાન',
  adherenceScoreText: 'પાલન સ્કોર',
  totalDoctors: 'કુલ ડોક્ટરો',
  totalPatients: 'કુલ દર્દીઓ',
  averageAdherence: 'સરેરાશ પાલન',
  criticalPatients: 'ગંભીર દર્દીઓ',
  todayUploads: 'આજના રિપોર્ટ અપલોડ',
  lowAdherencePatients: 'ઓછું પાલન કરતા દર્દીઓ',
  medicineExpiryAlerts: 'દવા સમાપ્તિ ચેતવણીઓ',
  inventorySummary: 'ઇન્વેન્ટરી સારાંશ',
  patientProfile: 'દર્દી પ્રોફાઇલ',
  dailyConsumption: 'દૈનિક વપરાશ',
  missedDoses: 'ચુકી ગયેલા ડોઝ',
  skippedMedicines: 'છોડી દીધેલી દવાઓ',
  weeklyAdherence: 'સાપ્તાહિક પાલન',
  monthlyAdherence: 'માસિક પાલન',
  medicineTimeline: 'દવા વપરાશની ટાઈમલાઈન',
  doctorNotes: 'ડોક્ટરની નોંધો',
  reportSummary: 'રિપોર્ટ સારાંશ',
  normalValues: 'સામાન્ય મૂલ્યો',
  abnormalValues: 'અસામાન્ય મૂલ્યો',
  criticalValues: 'નિર્ણાયક મૂલ્યો',
  explanationOfAbnormal: 'અસામાન્ય મૂલ્યોની સમજૂતી',
  possibleObservations: 'સંભવિત અવલોકનો',
  lifestyleRecs: 'જીવનશૈલી ભલામણો',
  suggestedFollowup: 'સૂચવેલ ફોલો-અપ પરીક્ષણો',
  overallHealthSummary: 'સમગ્ર સ્વાસ્થ્ય સારાંશ',
  aiNotice: 'AI દ્વારા તૈયાર કરાયેલ રિપોર્ટ સારાંશ. અંતિમ નિદાન હંમેશા લાયક તબીબી વ્યાવસાયિક દ્વારા થવું જોઈએ.'
};

const pa: LanguageLabels = {
  ...en,
  dashboard: 'ਡੈਸ਼ਬੋਰਡ', settings: 'ਸੈਟਿੰਗਜ਼', logout: 'ਲੌਗ ਆਉਟ', save: 'ਸੁਰੱਖਿਅਤ ਕਰੋ', cancel: 'ਰੱਦ ਕਰੋ', submit: 'ਜਮ੍ਹਾਂ ਕਰੋ', loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...', search: 'ਖੋਜੋ', language: 'ਭਾਸ਼ਾ', edit: 'ਸੋਧੋ', delete: 'ਮਿਟਾਓ', active: 'ਸਰਗਰਮ', verified: 'ਪ੍ਰਮਾਣਿਤ',
  login: 'ਲੌਗ ਇਨ', register: 'ਸ਼ੁਰੂ ਕਰੋ', signUp: 'ਸਾਈਨ ਅਪ',
  welcomeBack: 'ਜੀ ਆਇਆਂ ਨੂੰ', totalMedicines: 'ਕੁੱਲ ਦਵਾਈਆਂ', expiringSoon: 'ਜਲਦੀ ਖਤਮ ਹੋਣ ਵਾਲੀਆਂ', expired: 'ਮਿਆਦ ਪੁੱਗ ਚੁੱਕੀ', lowStock: 'ਘੱਟ ਸਟਾਕ', quickActions: 'ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ', scanQR: 'QR ਸਕੈਨ', bookTest: 'ਟੈਸਟ ਬੁੱਕ ਕਰੋ', addMedicine: 'ਦਵਾਈ ਜੋੜੋ', myMedicines: 'ਮੇਰੀਆਂ ਦਵਾਈਆਂ', confirmed: 'ਪੁਸ਼ਟੀ ਹੋਈ',
  medicineReminders: 'ਦਵਾਈ ਦੇ ਰੀਮਾਈਂਡਰ', restockRequests: 'ਰੀਸਟਾਕ ਬੇਨਤੀਆਂ', bloodTestBookings: 'ਬਲੱਡ ਟੈਸਟ ਬੁਕਿੰਗ', notifications: 'ਨੋਟੀਫਿਕੇਸ਼ਨ', profile: 'ਪ੍ਰੋਫਾਈਲ', personalInfo: 'ਨਿੱਜੀ ਜਾਣਕਾਰੀ', profileUpdated: 'ਪ੍ਰੋਫਾਈਲ ਅਪਡੇਟ ਹੋਈ',
  addReminder: 'ਰੀਮਾਈਂਡਰ ਜੋੜੋ', reminderAdded: 'ਰੀਮਾਈਂਡਰ ਜੋੜਿਆ ਗਿਆ', reminderDeleted: 'ਰੀਮਾਈਂਡਰ ਮਿਟਾਇਆ ਗਿਆ', reminderTime: 'ਰੀਮਾਈਂਡਰ ਸਮਾਂ', reminder: 'ਰੀਮਾਈਂਡਰ', timeToTakeMedicine: 'ਦਵਾਈ ਲੈਣ ਦਾ ਸਮਾਂ',
  markAllRead: 'ਸਾਰੇ ਪੜ੍ਹੇ ਹੋਏ ਮਾਰਕ ਕਰੋ', noNotifications: 'ਕੋਈ ਨੋਟੀਫਿਕੇਸ਼ਨ ਨਹੀਂ।',
  bookBloodTest: 'ਬਲੱਡ ਟੈਸਟ ਬੁੱਕ ਕਰੋ', testType: 'ਟੈਸਟ ਦੀ ਕਿਸਮ', selectTestType: 'ਟੈਸਟ ਦੀ ਕਿਸਮ ਚੁਣੋ', preferredDate: 'ਤਾਰੀਖ', preferredTime: 'ਸਮਾਂ', bookingCreated: 'ਬੁਕਿੰਗ ਸਫਲਤਾਪੂਰਵਕ ਹੋ ਗਈ',
  medicineName: 'ਦਵਾਈ ਦਾ ਨਾਮ', expiryDate: 'ਮਿਆਦ ਪੁੱਗਣ ਦੀ ਤਾਰੀਖ', quantity: 'ਮਾਤਰਾ', prescribedDoses: 'ਨਿਰਧਾਰਤ ਖੁਰਾਕ', medicineAdded: 'ਦਵਾਈ ਜੋੜੀ ਗਈ', adherence: 'ਦਵਾਈ ਦੀ ਪਾਲਣਾ', takeDose: 'ਖੁਰਾਕ ਲਓ', doseTaken: 'ਖੁਰਾਕ ਲਈ ਗਈ',
  pharmacyDashboard: 'ਫਾਰਮੇਸੀ ਡੈਸ਼ਬੋਰਡ', manageInventory: 'ਇਨਵੈਂਟਰੀ ਅਤੇ ਵਿਕਰੀ ਪ੍ਰਬੰਧਨ', totalItems: 'ਕੁੱਲ ਆਈਟਮਾਂ', sellMedicine: 'ਦਵਾਈ ਵੇਚੋ', addInventory: 'ਇਨਵੈਂਟਰੀ ਜੋੜੋ', csvUpload: 'CSV ਅਪਲੋਡ', accept: 'ਸਵੀਕਾਰ ਕਰੋ', reject: 'ਰੱਦ ਕਰੋ', fulfill: 'ਪੂਰਾ ਕਰੋ', fulfilled: 'ਪੂਰਾ ਹੋਇਆ', inventory: 'ਇਨਵੈਂਟਰੀ',
  diagnosticDashboard: 'ਡਾਇਗਨੌਸਟਿਕ ਸੈਂਟਰ ਡੈਸ਼ਬੋਰਡ', manageBookings: 'ਬੁਕਿੰਗ ਪ੍ਰਬੰਧਨ', pending: 'ਬਕਾਇਆ', accepted: 'ਸਵੀਕਾਰਿਆ', completed: 'ਪੂਰਾ ਹੋਇਆ', bookingRequests: 'ਬੁਕਿੰਗ ਬੇਨਤੀਆਂ', complete: 'ਪੂਰਾ ਕਰੋ', done: 'ਹੋ ਗਿਆ',
  openMap: 'ਨਕਸ਼ੇ ਵਿੱਚ ਖੋਲ੍ਹੋ', viewLocation: 'ਸਥਾਨ ਦੇਖੋ', location: 'ਸਥਾਨ', saveLocation: 'ਮੇਰਾ ਸਥਾਨ ਸੁਰੱਖਿਅਤ ਕਰੋ', locationSaved: 'ਸਥਾਨ ਸਫਲਤਾਪੂਰਵਕ ਸੁਰੱਖਿਅਤ ਹੋਇਆ',
  price: 'ਕੀਮਤ', discount: 'ਛੋਟ', finalPrice: 'ਆਖਰੀ ਕੀਮਤ', estimatedTime: 'ਅੰਦਾਜ਼ਨ ਸਮਾਂ', offerSent: 'ਆਫਰ ਭੇਜਿਆ ਗਿਆ', offersReceived: 'ਮਿਲੇ ਆਫਰ', newOffer: 'ਨਵਾਂ ਆਫਰ',
  safe: 'ਸੁਰੱਖਿਅਤ', expiring: 'ਮਿਆਦ ਖਤਮ ਹੋਣ ਵਾਲੀ',

  doctorDashboard: 'ਡਾਕਟਰ ਡੈਸ਼ਬੋਰਡ',
  myPatients: 'ਮੇਰੇ ਮਰੀਜ਼',
  reportAnalysis: 'ਮੈਡੀਕਲ ਰਿਪੋਰਟ ਵਿਸ਼ਲੇਸ਼ਣ',
  manageDoctors: 'ਡਾਕਟਰਾਂ ਦਾ ਪ੍ਰਬੰਧਨ',
  addDoctor: 'ਡਾਕਟਰ ਜੋੜੋ',
  editDoctor: 'ਡਾਕਟਰ ਜਾਣਕਾਰੀ ਸੋਧੋ',
  deleteDoctor: 'ਡਾਕਟਰ ਮਿਟਾਓ',
  resetPassword: 'ਪਾਸਵਰਡ ਰੀਸੈਟ ਕਰੋ',
  assignPatients: 'ਮਰੀਜ਼ ਨਿਯੁਕਤ ਕਰੋ',
  doctorName: 'ਡਾਕਟਰ ਦਾ ਨਾਮ',
  doctorId: 'ਡਾਕਟਰ ਆਈਡੀ',
  department: 'ਵਿਭਾਗ',
  specialization: 'ਮਹਾਰਤ',
  employeeId: 'ਕਰਮਚਾਰੀ ਆਈਡੀ',
  overallAdherence: 'ਕੁੱਲ ਦਵਾਈ ਪਾਲਣਾ ਦਰ',
  patientName: 'ਮਰੀਜ਼ ਦਾ ਨਾਮ',
  patientId: 'ਮਰੀਜ਼ ਆਈਡੀ',
  age: 'ਉਮਰ',
  gender: 'ਲਿੰਗ',
  assignedDate: 'ਨਿਯੁਕਤੀ ਦੀ ਤਾਰੀਖ',
  currentDiagnosis: 'ਮੌਜੂਦਾ ਨਿਦਾਨ',
  adherenceScoreText: 'ਪਾਲਣਾ ਸਕੋਰ',
  totalDoctors: 'ਕੁੱਲ ਡਾਕਟਰ',
  totalPatients: 'ਕੁੱਲ ਮਰੀਜ਼',
  averageAdherence: 'ਔਸਤ ਪਾਲਣਾ',
  criticalPatients: 'ਗੰਭੀਰ ਮਰੀਜ਼',
  todayUploads: 'ਅੱਜ ਦੇ ਰਿਪੋਰਟ ਅਪਲੋਡ',
  lowAdherencePatients: 'ਘੱਟ ਪਾਲਣਾ ਵਾਲੇ ਮਰੀਜ਼',
  medicineExpiryAlerts: 'ਦਵਾਈ ਖਤਮ ਹੋਣ ਦੇ ਅਲਰਟ',
  inventorySummary: 'ਇਨਵੈਂਟਰੀ ਸਾਰਾਂਸ਼',
  patientProfile: 'ਮਰੀਜ਼ ਪ੍ਰੋਫਾਈਲ',
  dailyConsumption: 'ਰੋਜ਼ਾਨਾ ਵਰਤੋਂ',
  missedDoses: 'ਖੁੰਝੀਆਂ ਹੋਈਆਂ ਖੁਰਾਕਾਂ',
  skippedMedicines: 'ਛੱਡੀਆਂ ਹੋਈਆਂ ਦਵਾਈਆਂ',
  weeklyAdherence: 'ਹਫ਼ਤਾਵਾਰੀ ਪਾਲਣਾ',
  monthlyAdherence: 'ਮਾਸਿਕ ਪਾਲਣਾ',
  medicineTimeline: 'ਦਵਾਈ ਦੀ ਵਰਤੋਂ ਦੀ ਟਾਈਮਲਾਈਨ',
  doctorNotes: 'ਡਾਕਟਰ ਦੇ ਨੋਟਸ',
  reportSummary: 'ਰਿਪੋਰਟ ਸਾਰਾਂਸ਼',
  normalValues: 'ਸਧਾਰਣ ਮੁੱਲ',
  abnormalValues: 'ਅਸਧਾਰਣ ਮੁੱਲ',
  criticalValues: 'ਨਾਜ਼ੁਕ ਮੁੱਲ',
  explanationOfAbnormal: 'ਅਸਧਾਰਣ ਮੁੱਲਾਂ ਦੀ ਵਿਆਖਿਆ',
  possibleObservations: 'ਸੰਭਾਵਿਤ ਨਿਰੀਖਣ',
  lifestyleRecs: 'ਜੀਵਨਸ਼ੈਲੀ ਦੀਆਂ ਸਿਫ਼ਾਰਸ਼ਾਂ',
  suggestedFollowup: 'ਸੁਝਾਏ ਗਏ ਫਾਲੋ-ਅੱਪ ਟੈਸਟ',
  overallHealthSummary: 'ਕੁੱਲ ਸਿਹਤ ਸਾਰਾਂਸ਼',
  aiNotice: 'AI ਦੁਆਰਾ ਤਿਆਰ ਕੀਤਾ ਰਿਪੋਰਟ ਸਾਰਾਂਸ਼। ਅੰਤਿਮ ਨਿਦਾਨ ਹਮੇਸ਼ਾ ਇੱਕ ਯੋਗ ਡਾਕਟਰ ਦੁਆਰਾ ਕੀਤਾ ਜਾਣਾ ਚਾਹੀਦਾ ਹੈ।'
};

const bn: LanguageLabels = {
  ...en,
  dashboard: 'ড্যাশবোর্ড', settings: 'সেটিংস', logout: 'লগ আউট', save: 'সংরক্ষণ করুন', cancel: 'বাতিল', submit: 'জমা দিন', loading: 'লোড হচ্ছে...', search: 'অনুসন্ধান', language: 'ভাষা', edit: 'সম্পাদনা', delete: 'মুছুন', active: 'সক্রিয়', verified: 'যাচাইকৃত',
  login: 'লগ ইন', register: 'শুরু করুন', signUp: 'সাইন আপ',
  welcomeBack: 'স্বাগতম', totalMedicines: 'মোট ওষুধ', expiringSoon: 'দ্রুত মেয়াদউত্তীর্ণ হবে', expired: 'মেয়াদউত্তীর্ণ', lowStock: 'কম স্টক', quickActions: 'দ্রুত পদক্ষেপ', scanQR: 'QR স্ক্যান', bookTest: 'টেস্ট বুক করুন', addMedicine: 'ওষুধ যোগ করুন', myMedicines: 'আমার ওষুধ', confirmed: 'নিশ্চিত',
  medicineReminders: 'ওষুধের অনুস্মারক', restockRequests: 'পুনরায় স্টক করার অনুরোধ', bloodTestBookings: 'রক্ত পরীক্ষার বুকিং', notifications: 'বিজ্ঞপ্তি', profile: 'প্রোফাইল', personalInfo: 'ব্যক্তিগত তথ্য', profileUpdated: 'প্রোফাইল আপডেট হয়েছে',
  addReminder: 'অনুস্মারক যোগ করুন', reminderAdded: 'অনুস্মারক যোগ করা হয়েছে', reminderDeleted: 'অনুস্মারক মুছে ফেলা হয়েছে', reminderTime: 'অনুস্মারক সময়', reminder: 'অনুস্মারক', timeToTakeMedicine: 'ওষুধ খাওয়ার সময়',
  markAllRead: 'সব পড়া হয়েছে চিহ্নিত করুন', noNotifications: 'কোন বিজ্ঞপ্তি নেই।',
  bookBloodTest: 'রক্ত পরীক্ষা বুক করুন', testType: 'পরীক্ষার ধরন', selectTestType: 'পরীক্ষার ধরন নির্বাচন করুন', preferredDate: 'তারিখ', preferredTime: 'সময়', bookingCreated: 'বুকিং সফলভাবে সম্পন্ন হয়েছে',
  medicineName: 'ওষুধের নাম', expiryDate: 'মেয়াদ শেষ হওয়ার তারিখ', quantity: 'পরিমাণ', prescribedDoses: 'নির্ধারিত ডোজ', medicineAdded: 'ওষুধ যোগ করা হয়েছে', adherence: 'ওষুধ খাওয়ার অনুবর্তিতা', takeDose: 'ডোজ নিন', doseTaken: 'ডোজ নেওয়া হয়েছে',
  pharmacyDashboard: 'ফার্মেসি ড্যাশবোর্ড', manageInventory: 'ইনভেন্টরি ও বিক্রি পরিচালনা', totalItems: 'মোট আইটেম', sellMedicine: 'ওষুধ বিক্রি করুন', addInventory: 'ইনভেন্টরি যোগ করুন', csvUpload: 'CSV আপলোড', accept: 'স্বীকার করুন', reject: 'প্রত্যাখ্যান করুন', fulfill: 'সম্পন্ন করুন', fulfilled: 'সম্পন্ন হয়েছে', inventory: 'ইনভেন্টরি',
  diagnosticDashboard: 'ডায়াগনস্টিক সেন্টার ড্যাশবোর্ড', manageBookings: 'বুকিং পরিচালনা করুন', pending: 'বকেয়া', accepted: 'গৃহীত', completed: 'সম্পন্ন', bookingRequests: 'বুকিং অনুরোধ', complete: 'সম্পন্ন করুন', done: 'সম্পন্ন',
  openMap: 'মানচিত্রে খুলুন', viewLocation: 'অবস্থান দেখুন', location: 'অবস্থান', saveLocation: 'আমার অবস্থান সংরক্ষণ করুন', locationSaved: 'অবস্থান সফলভাবে সংরক্ষিত হয়েছে',
  price: 'মূল্য', discount: 'ছাড়', finalPrice: 'চূড়ান্ত মূল্য', estimatedTime: 'আনুমানিক সময়', offerSent: 'অফার পাঠানো হয়েছে', offersReceived: 'প্রাপ্ত অফার', newOffer: 'নতুন অফার',
  safe: 'নিরাপদ', expiring: 'মেয়াদ শেষ হতে চলেছে',

  doctorDashboard: 'ডাক্তার ড্যাশবোর্ড',
  myPatients: 'আমার রোগী',
  reportAnalysis: 'মেডিকেল রিপোর্ট বিশ্লেষণ',
  manageDoctors: 'ডাক্তারদের পরিচালনা',
  addDoctor: 'ডাক্তার যোগ করুন',
  editDoctor: 'ডাক্তার তথ্য সম্পাদনা করুন',
  deleteDoctor: 'ডাক্তার মুছুন',
  resetPassword: 'পাসওয়ার্ড রিসেট করুন',
  assignPatients: 'রোগী বরাদ্দ করুন',
  doctorName: 'ডাক্তারের নাম',
  doctorId: 'ডাক্তার আইডি',
  department: 'বিভাগ',
  specialization: 'বিশেষজ্ঞতা',
  employeeId: 'কর্মচারী আইডি',
  overallAdherence: 'সামগ্রিক ওষুধ খাওয়ার অনুবর্তিতা',
  patientName: 'রোগীর নাম',
  patientId: 'রোগী আইডি',
  age: 'বয়স',
  gender: 'লিঙ্গ',
  assignedDate: 'বরাদ্দের তারিখ',
  currentDiagnosis: 'বর্তমান রোগ নির্ণয়',
  adherenceScoreText: 'অনুবর্তিতা স্কোর',
  totalDoctors: 'মোট ডাক্তার',
  totalPatients: 'মোট রোগী',
  averageAdherence: 'গড় অনুবর্তিতা',
  criticalPatients: 'গুরুতর রোগী',
  todayUploads: 'আজকের রিপোর্ট আপলোড',
  lowAdherencePatients: 'কম অনুবর্তিতার রোগী',
  medicineExpiryAlerts: 'ওষুধের মেয়াদ শেষ হওয়ার অ্যালার্ট',
  inventorySummary: 'ইনভেন্টরি সারাংশ',
  patientProfile: 'রোগী প্রোফাইল',
  dailyConsumption: 'দৈনিক ব্যবহার',
  missedDoses: 'বাদ পড়া ডোজ',
  skippedMedicines: 'উপেক্ষিত ওষুধ',
  weeklyAdherence: 'সাপ্তাহিক অনুবর্তিতা',
  monthlyAdherence: 'মাসিক অনুবর্তিতা',
  medicineTimeline: 'ওষুধ গ্রহণের টাইমলাইন',
  doctorNotes: 'ডাক্তারের নোট',
  reportSummary: 'রিপোর্ট সারাংশ',
  normalValues: 'স্বাভাবিক মান',
  abnormalValues: 'অস্বাভাবিক মান',
  criticalValues: 'গুরুতর মান',
  explanationOfAbnormal: 'অস্বাভাবিক মানের ব্যাখ্যা',
  possibleObservations: 'সম্ভাব্য পর্যবেক্ষণ',
  lifestyleRecs: 'জীবনযাত্রার সুপারিশ',
  suggestedFollowup: 'প্রস্তাবিত ফলো-আপ পরীক্ষা',
  overallHealthSummary: 'সামগ্রিক স্বাস্থ্য সারাংশ',
  aiNotice: 'AI দ্বারা তৈরি করা রিপোর্ট সারাংশ। চূড়ান্ত রোগ নির্ণয় সর্বদা একজন যোগ্যতাসম্পন্ন চিকিৎসকের দ্বারা করা উচিত।'
};

const translations: Record<Language, LanguageLabels> = { en, hi, ur, te, kn, ta, ml, mr, gu, pa, bn };

const languageNames: Record<Language, string> = {
  en: 'English',
  hi: 'हिंदी',
  ur: 'اردو',
  te: 'తెలుగు',
  kn: 'ಕನ್ನಡ',
  ta: 'தமிழ்',
  ml: 'മലയാളം',
  mr: 'मराठी',
  gu: 'ગુજરાતી',
  pa: 'ਪੰਜਾਬੀ',
  bn: 'বাংলা',
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  languageNames: Record<Language, string>;
  allLanguages: Language[];
}

const defaultLanguageContext: LanguageContextType = {
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => en[key] || key,
  languageNames,
  allLanguages: Object.keys(translations) as Language[],
};

const LanguageContext = createContext<LanguageContextType>(defaultLanguageContext);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');
  let authContext: { user: any; profile: any } = { user: null, profile: null };
  try {
    authContext = useAuth();
  } catch {
    // Auth not available yet
  }
  const { user, profile } = authContext;

  useEffect(() => {
    if (profile?.language) {
      const lang = profile.language as Language;
      if (translations[lang]) setLanguageState(lang);
    }
  }, [profile]);

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    if (user) {
      await supabase.from('profiles').update({ language: lang } as any).eq('user_id', user.id);
    }
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languageNames, allLanguages: Object.keys(translations) as Language[] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
